name: aneris
channels:
 - conda-forge
 - nodefaults
dependencies:
 - python=3.8
 - libgl
 - pip:
    - absl-py==2.1.0
    - anyio==4.6.2
    - anywidget==0.9.13
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - asttokens==2.0.5
    - astunparse==1.6.3
    - async-lru==2.0.4
    - attrs==24.2.0
    - Babel==2.11.0
    - beautifulsoup4==4.12.3
    - bleach==4.1.0
    - Brotli==1.0.9
    - certifi==2024.8.30
    - cffi==1.17.1
    - charset-normalizer==3.3.2
    - comm==0.2.1
    - contourpy
    - cycler==0.12.1
    - dataclasses-json==0.6.7
    - debugpy==1.6.7
    - decorator==5.1.1
    - defusedxml==0.7.1
    - dill==0.3.9
    - et_xmlfile==2.0.0
    - executing==0.8.3
    - fastjsonschema==2.16.2
    - filelock==3.16.1
    - filetype==1.2.0
    - fire==0.7.0
    - flatbuffers==24.3.25
    - fonttools==4.54.1
    - fsspec==2024.10.0
    - gast==0.6.0
    - gitdb==4.0.11
    - GitPython==3.1.43
    - google-pasta==0.2.0
    - grpcio==1.67.1
    - h11==0.14.0
    - h5py
    - httpcore==1.0.2
    - httpx==0.27.0
    - idna==3.7
    - imageio
    - ipykernel==6.29.5
    - ipython
    - ipywidgets==8.1.2
    - jedi==0.19.1
    - Jinja2==3.1.4
    - joblib==1.4.2
    - json5==0.9.25
    - jsonschema==4.23.0
    - jsonschema-specifications==2023.7.1
    - jupyter==1.0.0
    - jupyter_bbox_widget==0.6.0
    - jupyter_client==8.6.0
    - jupyter-console==6.6.3
    - jupyter_core==5.7.2
    - jupyter-events==0.10.0
    - jupyter-lsp==2.2.0
    - jupyter_server==2.14.1
    - jupyter_server_terminals==0.4.4
    - jupyterlab==4.2.5
    - jupyterlab-pygments==0.1.2
    - jupyterlab_server==2.27.3
    - jupyterlab-widgets==3.0.10
    - keras
    - kiwisolver==1.4.7
    - lazy_loader==0.4
    - libclang==18.1.1
    - mahotas==1.4.18
    - Markdown==3.7
    - markdown-it-py==3.0.0
    - MarkupSafe==2.1.3
    - marshmallow
    - matplotlib
    - matplotlib-inline==0.1.6
    - mdurl==0.1.2
    - mistune==2.0.4
    - ml-dtypes
    - mpmath==1.3.0
    - mypy-extensions==1.0.0
    - namex==0.0.8
    - nbclient==0.8.0
    - nbconvert==7.16.4
    - nbformat==5.10.4
    - nest-asyncio==1.6.0
    - networkx
    - notebook==7.2.2
    - notebook_shim==0.2.3
    - numpy
    - nvidia-cublas-cu12==12.4.5.8
    - nvidia-cuda-cupti-cu12==12.4.127
    - nvidia-cuda-nvrtc-cu12==12.4.127
    - nvidia-cuda-runtime-cu12==12.4.127
    - nvidia-cudnn-cu12==9.1.0.70
    - nvidia-cufft-cu12==11.2.1.3
    - nvidia-curand-cu12==10.3.5.147
    - nvidia-cusolver-cu12==11.6.1.9
    - nvidia-cusparse-cu12==12.3.1.170
    - nvidia-nccl-cu12==2.21.5
    - nvidia-nvjitlink-cu12==12.4.127
    - nvidia-nvtx-cu12==12.4.127
    - opencv-python==4.10.0.84
    - opencv-python-headless==4.10.0.84
    - openpyxl==3.1.5
    - opt_einsum==3.4.0
    - optree==0.13.1
    - overrides==7.4.0
    - packaging==24.1
    - pandas
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow
    - pip==24.2
    - platformdirs==3.10.0
    - ply==3.11
    - prometheus-client==0.14.1
    - prompt-toolkit==3.0.43
    - protobuf
    - psutil==5.9.0
    - psygnal==0.11.1
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - py-cpuinfo==9.0.0
    - pycparser==2.21
    - pyefd==1.6.0
    - Pygments==2.15.1
    - pyparsing
    - PyQt5==5.15.10
    - PyQt5-sip==12.13.0
    - PySocks==1.7.1
    - python-dateutil==2.9.0.post0
    - python-dotenv==1.0.1
    - python-json-logger==2.0.7
    - pytz==2024.1
    - PyWavelets
    - PyYAML==6.0.2
    - pyzmq==25.1.2
    - qtconsole==5.6.0
    - QtPy==2.4.1
    - rawpy
    - referencing==0.30.2
    - requests==2.32.3
    - requests-toolbelt==1.0.0
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rich==13.9.4
    - roboflow==1.1.49
    - rpds-py==0.10.6
    - scikit-image
    - scikit-learn
    - scipy
    - seaborn==0.13.2
    - segment_anything==1.0
    - Send2Trash==1.8.2
    - setuptools==75.1.0
    - sip==6.7.12
    - six==1.16.0
    - smmap==5.0.1
    - sniffio==1.3.0
    - soupsieve==2.5
    - stack-data==0.2.0
    - supervision==0.24.0
    - sympy==1.13.1
    - tensorboard
    - tensorboard-data-server
    - tensorflow
    - termcolor
    - terminado==0.17.1
    - thop==0.1.1.post2209072238
    - threadpoolctl==3.5.0
    - tifffile
    - tinycss2==1.2.1
    - torch
    - torchvision
    - tornado==6.4.1
    - tqdm==4.67.0
    - traitlets==5.14.3
    - triton==3.1.0
    - typing_extensions==4.11.0
    - typing-inspect==0.9.0
    - tzdata==2024.2
    - ultralytics==8.3.28
    - ultralytics-thop==2.0.10
    - ultralytics-yolov5==0.1.1
    - urllib3==2.2.3
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - websocket-client==1.8.0
    - Werkzeug
    - wheel==0.44.0
    - widgetsnbextension==4.0.10
    - wrapt==1.17.0
